[versions]
springframeworkBoot = "3.4.1"
springDependencyManagement = "1.1.7"
spotless = "7.0.1"
commonsLang = "3.17.0"
commonsCollections = "4.4"
jsoup = "1.18.3"
gson = "2.11.0"

[libraries]
spring-boot-starter-batch = { group = "org.springframework.boot", name = "spring-boot-starter-batch" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-batch-test = { group = "org.springframework.batch", name = "spring-batch-test" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang" }
commons-collections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commonsCollections" }
h2 = { group = "com.h2database", name = "h2" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[bundles]
apache-commons = ["commons-lang3", "commons-collections4"]

[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "springframeworkBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
