name: JSON Formatter

on:
  pull_request:
    paths:
      - "**/*.json"
    types:
      - opened # PR作成時
      - synchronize # PRのコミット更新時

jobs:
  format-json:
    name: Format JSON
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Format JSON Files with jq
        id: formatJson
        run: |
          # JSONファイルをフォーマットする
          find . -name "*.json" | while read file; do
            jq . "$file" > tmp.json && mv tmp.json "$file"
          done

      - name: Commit & Push
        id: commit_push
        if: steps.formatJson.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: "chore: JSONファイルをフォーマット"
