name: YAML Formatter

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
    types:
      - opened # PR作成時
      - synchronize # PRのコミット更新時

jobs:
  format-yaml:
    name: Format YAML
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Format YAML Files
        id: formatYaml
        uses: yk-lab/yamlfmt-action@09b479266d67ef9a3baa347affa8320204271677 # v1.0.0
        with:
          path: ".github/workflows"
        continue-on-error: true

      - name: Commit & Push
        id: commit_push
        if: steps.formatYaml.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: "chore: YAMLファイルをフォーマット"
